apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sushi-digital-human.fullname" . }}-secrets
  labels:
    {{- include "sushi-digital-human.labels" . | nindent 4 }}
type: Opaque
stringData:
  dashscope-api-key: {{ .Values.secrets.dashscopeApiKey | quote }}
  secret-key: {{ .Values.secrets.secretKey | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | quote }}
